name: Build LunarCore2
on:
  workflow_dispatch: ~
  push:
    paths:
      - "**.java"
    branches:
      - main
      - development
  pull_request:
    paths:
      - "**.java"
    types:
      - opened
      - synchronize
      - reopened
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
        - name: Get current date
          id: date
          run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        - name: Test with environment variables
          run: echo $TAG_NAME - $RELEASE_NAME
          env:
            TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
            RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: '17'
        - name: Cache gradle files
          uses: actions/cache@v2
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
              ./.gradle/loom-cache
            key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle', 'gradle.properties', '**/*.accesswidener') }}
            restore-keys: |
              ${{ runner.os }}-gradle-
        - name: Run Gradle
          run: rm -rf src/main/java/emu/lunarcore/server/packet/send/PacketServerAnnounceNotify.java && cp nwe/PacketServerAnnounceNotify.java src/main/java/emu/lunarcore/server/packet/send/PacketServerAnnounceNotify.java && rm -rf src/main/java/emu/lunarcore/server/game/GameServer.java && cp nwe/GameServer.java src/main/java/emu/lunarcore/server/game/GameServer.java &&rm -rf src/main/java/emu/lunarcore/LunarCore.java && cp nwe/LunarCore.java src/main/java/emu/lunarcore/LunarCore.java  && cp nwe/Config.java src/main/java/emu/lunarcore/Config.java && rm -rf src/main/java/emu/lunarcore/server/http/HttpServer.java && cp nwe/HttpServer.java src/main/java/emu/lunarcore/server/http/HttpServer.java && cat src/main/java/emu/lunarcore/server/http/HttpServer.java && chmod +x gradlew && ./gradlew && ./gradlew jar
          
        - name: Upload build
          uses: actions/upload-artifact@v3
          with:
            name: LunarCore
            path: LunarCore.jar
        - name: Release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: LunarCore.jar
            file_glob: true
            tag: ${{ steps.date.outputs.date }}
            overwrite: true
